modLoader = "javafml"
loaderVersion = "[1,)"
#issueTrackerURL = ""
license = "MIT (code), All Rights Reserved (art, see LICENSE-ASSETS)"

[[mods]]
modId = "barro"
version = "${version}"
displayName = "Barro"
authors = "kevdev-code"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
#logoFile = ""

[[dependencies.barro]]
modId = "neoforge"
type = "required"
versionRange = "[26.1.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.barro]]
modId = "minecraft"
type = "required"
versionRange = "[26.1.2,26.2)"
ordering = "NONE"
side = "BOTH"

[[dependencies.barro]]
modId = "architectury"
type = "required"
versionRange = "[20.0.12,)"
ordering = "AFTER"
side = "BOTH"
